In [1]:
# Import the libraries

import time 
import sys
import numpy as np 

import matplotlib.pyplot as plt
%matplotlib inline  

In [2]:
# Plotting functions

def Plotvec1(u, z, v):
    
    ax = plt.axes()
    ax.arrow(0, 0, *u, head_width=0.05, color='r', head_length=0.1)
    plt.text(*(u + 0.1), 'u')
    
    ax.arrow(0, 0, *v, head_width=0.05, color='b', head_length=0.1)
    plt.text(*(v + 0.1), 'v')
    ax.arrow(0, 0, *z, head_width=0.05, head_length=0.1)
    plt.text(*(z + 0.1), 'z')
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)

def Plotvec2(a,b):
    ax = plt.axes()
    ax.arrow(0, 0, *a, head_width=0.05, color ='r', head_length=0.1)
    plt.text(*(a + 0.1), 'a')
    ax.arrow(0, 0, *b, head_width=0.05, color ='b', head_length=0.1)
    plt.text(*(b + 0.1), 'b')
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)

In [3]:
# Create a python list

a = ["0", 1, "two", "3", 4]

In [4]:

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: two
a[3]: 3
a[4]: 4


In [5]:
import numpy as np 

In [6]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [7]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [8]:
type(a)

numpy.ndarray

In [9]:
a.dtype

dtype('int64')

In [10]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])

In [11]:
c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [12]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

In [13]:
# Assign the 5th element to 0

c[4] = 0
c

array([100,   1,   2,   3,   0])

In [14]:
d = c[1:4]
d

array([1, 2, 3])

In [15]:
c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

In [16]:
# Create the index list

select = [0, 2, 3]
d = c[select]
d

array([100,   2, 300])

In [17]:
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [18]:
a.size

5

In [19]:
a.ndim

1

In [20]:
a.shape

(5,)

In [21]:
a = np.array([1, -1, 1, -1])

In [22]:
mean = a.mean()
mean

0.0

In [23]:
# Get the standard deviation of numpy array

standard_deviation=a.std()
standard_deviation

1.0

In [24]:
# Create a numpy array

b = np.array([-1, 2, 3, 4, 5])
b

array([-1,  2,  3,  4,  5])

In [25]:
# Get the biggest value in the numpy array

max_b = b.max()
max_b

5

In [26]:
# Get the smallest value in the numpy array

min_b = b.min()
min_b

-1

In [27]:
import numpy as np
u = np.array([1,2])
v = np.array([3,4])
u-v

array([-2, -2])

In [28]:
z = np.array([2, 4])
z * 2

array([4, 8])

In [29]:
a = np.array ([1, 2, 3, 4, 5])
b = np.array ([1, 0, 1, 0, 1])
a * b


array([1, 0, 3, 0, 5])