In [1]:
# Import the libraries

import numpy as np 
import matplotlib.pyplot as plt

In [2]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [3]:
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [4]:
A.ndim

2

In [5]:
A.shape

(3, 3)

In [6]:
A.size

9

In [7]:
A[1, 2]

A[1][2]

23

In [8]:
A[1, 2]

23

In [9]:
A[1][2]

23

In [10]:
X = np.array([[1, 0], [0, 1]]) 
X
Y = np.array([[2, 1], [1, 2]]) 
Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [11]:
A = np.array([[0, 1, 1], [1, 0, 1]])
B = np.array([[1, 1], [1, 1], [-1, 1]])
Z = np.dot(A,B)

In [12]:
Z


array([[0, 2],
       [0, 2]])

In [13]:

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [14]:
C.T

array([[1, 2, 3],
       [1, 2, 3]])